export const TOURNAMENT_CONFIGS = {
  pga2026: {
    id: "pga2026",
    active: true,
    appTitle: "Major Fantasy Leaderboard",
    productLabel: "Fantasy Golf Major",
    displayName: "2026 PGA Championship",
    majorName: "PGA Championship",
    espnEventMatchers: ["pga championship"],
    espnScoreboardUrl: "https://site.api.espn.com/apis/site/v2/sports/golf/pga/scoreboard",
    courseName: "Aronimink Golf Club",
    coursePars: [4, 4, 4, 4, 3, 4, 4, 3, 5, 4, 4, 4, 4, 3, 4, 5, 3, 4],
    firstTeeIso: "2026-05-14T03:45:00-07:00",
    entryLockIso: "2026-05-14T03:45:00-07:00",
    sheetId: "1F4iS2djEYYvhBRrkqfmCF94vQ9EFGFas7NmmMr3r64M",
    sheetName: "Sheet1",
    timezone: "America/Los_Angeles",
    scoreRefreshMs: 60000,
    scoreCacheSeconds: 45,
    roundDates: {
      1: "2026-05-14",
      2: "2026-05-15",
      3: "2026-05-16",
      4: "2026-05-17",
    },
    prizes: [
      { place: 1, placeLabel: "1st", label: "Champion", prize: "$100", cashValue: 100 },
      { place: 2, placeLabel: "2nd", label: "Runner-up", prize: "$30", cashValue: 30 },
      { place: 3, placeLabel: "3rd", label: "Podium", prize: "$20", cashValue: 20 },
      { place: 4, placeLabel: "4th", label: "Bubble prize", prize: "US Open entry" },
    ],
  },
  masters: {
    id: "masters",
    active: false,
    appTitle: "Major Fantasy Leaderboard",
    productLabel: "Fantasy Golf Major",
    displayName: "Masters Tournament",
    majorName: "Masters",
    espnEventMatchers: ["masters"],
    courseName: "Augusta National Golf Club",
    coursePars: [],
    prizes: [],
  },
  usOpen: {
    id: "usOpen",
    active: false,
    appTitle: "Major Fantasy Leaderboard",
    productLabel: "Fantasy Golf Major",
    displayName: "U.S. Open",
    majorName: "U.S. Open",
    espnEventMatchers: ["u.s. open", "us open"],
    courseName: "TBA",
    coursePars: [],
    prizes: [],
  },
  theOpen: {
    id: "theOpen",
    active: false,
    appTitle: "Major Fantasy Leaderboard",
    productLabel: "Fantasy Golf Major",
    displayName: "The Open Championship",
    majorName: "The Open",
    espnEventMatchers: ["open championship", "the open"],
    courseName: "TBA",
    coursePars: [],
    prizes: [],
  },
};

export const ACTIVE_TOURNAMENT_ID = "pga2026";
export const tournamentConfig = TOURNAMENT_CONFIGS[ACTIVE_TOURNAMENT_ID];

